
//! Autogenerated weights for `liganite_publish`
//!
//! THIS FILE WAS AUTO-GENERATED USING THE SUBSTRATE BENCHMARK CLI VERSION 46.0.0
//! DATE: 2025-03-23, STEPS: `50`, REPEAT: `20`, LOW RANGE: `[]`, HIGH RANGE: `[]`
//! WORST CASE MAP SIZE: `1000000`
//! HOSTNAME: `kalan-x1x`, CPU: `12th Gen Intel(R) Core(TM) i7-12800H`
//! WASM-EXECUTION: `Compiled`, CHAIN: `None`, DB CACHE: 1024

// Executed Command:
// frame-omni-bencher
// v1
// benchmark
// pallet
// --runtime
// ./target/production/wbuild/liganite-runtime/liganite_runtime.compact.compressed.wasm
// --pallet
// liganite_publish
// --extrinsic
// *
// --output
// ./runtime/src/weights/liganite_publish.rs

#![cfg_attr(rustfmt, rustfmt_skip)]
#![allow(unused_parens)]
#![allow(unused_imports)]
#![allow(missing_docs)]

use frame_support::{traits::Get, weights::Weight};
use core::marker::PhantomData;

/// Weight functions for `liganite_publish`.
pub struct WeightInfo<T>(PhantomData<T>);
impl<T: frame_system::Config> liganite_publish::WeightInfo for WeightInfo<T> {
	/// Storage: `Publish::Publishers` (r:1 w:1)
	/// Proof: `Publish::Publishers` (`max_values`: None, `max_size`: Some(300), added: 2775, mode: `MaxEncodedLen`)
	/// The range of component `a` is `[1, 128]`.
	/// The range of component `b` is `[0, 128]`.
	fn publisher_add(_a: u32, _b: u32, ) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `6`
		//  Estimated: `3765`
		// Minimum execution time: 6_675_000 picoseconds.
		Weight::from_parts(8_362_303, 0)
			.saturating_add(Weight::from_parts(0, 3765))
			.saturating_add(T::DbWeight::get().reads(1))
			.saturating_add(T::DbWeight::get().writes(1))
	}
}
